### ISSUE TITLE
Memory leaks due to unsafe swizzling?

### ISSUE THREAD

**Issue by rsanchezsaez** [mattt/AnimatedGIFImageSerialization#11]
Hi,

Under some circumstances, Xcode's Memory Leaks Instrument seems to report leaks when using _AnimatedGIFImageSerialization_ in combination with _Crashlytics_. I don't know if those are actual leaks or not. All of these have in common _Crashlytics_ and _AnimatedGIFImageSerialization_:

![screen shot 2014-10-16 at 12 39 15](https://cloud.githubusercontent.com/assets/444313/4661857/652785b6-5529-11e4-977f-28d64810b73d.png)

The leaks seem to go away if you replace _AnimatedGIFImageSerialization_'s swizzling by _JRSwizzle_, which seems to be safer for subclassing and inheritance:

```
[self jr_swizzleMethod:@selector(imageNamed:) withMethod:@selector(animated_gif_imageNamed:) error:nil];
[self jr_swizzleMethod:@selector(imageWithData:) withMethod:@selector(animated_gif_imageWithData:) error:nil];
[self jr_swizzleMethod:@selector(imageWithData:scale:) withMethod:@selector(animated_gif_imageWithData:scale:) error:nil];
[self jr_swizzleMethod:@selector(imageWithContentsOfFile:) withMethod:@selector(animated_gif_imageWithContentsOfFile:) error:nil];
[self jr_swizzleMethod:@selector(initWithContentsOfFile:) withMethod:@selector(animated_gif_initWithContentsOfFile:) error:nil];
[self jr_swizzleMethod:@selector(initWithData:) withMethod:@selector(animated_gif_initWithData:) error:nil];
[self jr_swizzleMethod:@selector(initWithData:scale:) withMethod:@selector(animated_gif_initWithData:scale:) error:nil];
```

**Comment by bwhiteley** [comment]
I'm seeing the same thing as @rsanchezsaez. Every image is leaked unless I switch to jr_swizzleMethod. I have an image-intensive app, and the OOM-killer says it's so in addition to Instruments.

**Comment by kostiadombrovsky** [comment]
I have the same issue - imageWithData = leaks, UIImageWithAnimatedGIFData no leaks.

**Comment by kostiadombrovsky** [comment]
![screen shot 2016-01-29 at 16 19 50](https://cloud.githubusercontent.com/assets/617285/12691917/6c89aed0-c6a5-11e5-9c90-40cdfd868c67.png)

**Comment by kostiadombrovsky** [comment]
@rsanchezsaez @bwhiteley it seems that the reason why JRSwizzle helped is that you're using it wrong.
```
[self jr_swizzleMethod:@selector(imageNamed:) withMethod:@selector(animated_gif_imageNamed:) error:nil];
[self jr_swizzleMethod:@selector(imageWithData:) withMethod:@selector(animated_gif_imageWithData:) error:nil];
[self jr_swizzleMethod:@selector(imageWithData:scale:) withMethod:@selector(animated_gif_imageWithData:scale:) error:nil];
[self jr_swizzleMethod:@selector(imageWithContentsOfFile:) withMethod:@selector(animated_gif_imageWithContentsOfFile:) error:nil];
```
`jr_swizzleMethod` fails actually if you try to use it for class methods. If you use `jr_swizzleClassMethod`: then it leaks as does @mattt 's implementation.

The whole thing works because `[UIImage imageWithData:]` is actually `[[UIImage alloc] initWithData:]` under the hood.

Still weird why it leaks 😓

**Comment by pionl** [comment]
Still getting huge leaks, every image is leaked. When I remove the library, no leaks.

**Comment by dmitry-ivanov-rlt** [comment]
I switched pull to refresh control to use YYImage for gifs

**Comment by pionl** [comment]
@dmitry-ivanov-rlt Hi Dmitry, thanks for the advice, will try think about switch. Unfortunately I need to enable saving GIF to a file and downloading it via AFNetworking (probably i can change the usage to get NSData instead of UIImage)
