### ISSUE TITLE
Clean the code.

### ISSUE THREAD

**Issue by mariovillamizar** [mattt/AnimatedGIFImageSerialization#17]
In the .m file, on line 71 I get a warning: "The code will never be executed". Please clean the code, because the warnings are very uncomfortable.

**Comment by yurijmi** [comment]
Done that in #21 
Until repo's author approves it you can use this in your Podfile:
```pod 'AnimatedGIFImageSerialization', git: 'https://github.com/yurijmi/AnimatedGIFImageSerialization.git'```

**Comment by Codeido** [comment]
Mattt, please accept this pull request. I hate to see warning in my project!
Thanks

**Comment by mattt** [comment]
Really sorry about that. This is fixed by 38c90c8eeb56878a332875607447721f88fc453b and 87ed94538b67cfad1a99de60741a2e3e5664bab3.
