### ISSUE TITLE
Exception (endless loop) when used in tests under Xcode 7.0 GM

### ISSUE THREAD

**Issue by plaetzchen** [mattt/AnimatedGIFImageSerialization#18]
I get a exception with endless loop when AnimatedGIFImiageSerialization is imported in classes that are used in unit tests.

The loop happens with this method: + (UIImage *)animated_gif_imageNamed:(NSString *)name __attribute__((objc_method_family(new))) {

**Comment by bgerstle** [comment]
I found out the problem the code was being loaded twice, causing `+load` to be called twice.  You can set a breakpoint to confirm this is also your problem.  You might also see logs in the console about two implementations of a class being loaded, and the version chosen being undefined.  We're using CocoaPods, and I fixed the issue by setting the `:exclusive` flag to `true`:

``` ruby
target 'WikipediaUnitTests', :exclusive => true do
  pod 'OCMockito', '~> 1.4'
  pod 'OCHamcrest', '~> 4.1'
  pod 'Nocilla'
  pod 'FBSnapshotTestCase/Core', '~> 2.0.3'
end
```

**Comment by plaetzchen** [comment]
This doesn't help unfortunately. This is my Podfile (shortened)

````
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.1'

workspace './MyApp'

inhibit_all_warnings!

def import_pods
    (...)
    pod 'AnimatedGIFImageSerialization'
   (...)
end

target :'MyApp' do
    import_pods
end

target 'MyAppTests' do
    import_pods
    pod 'OCMock', '~> 3.1'
    pod 'FBSnapshotTestCase', '< 2.0'
end
````

**Comment by bgerstle** [comment]
@plaetzchen what you're doing is functionally equivalent to having `:exclusive` set to false. Are you tests hosted within your app?  If you're not sure, check the "Genera" section of your test target's build settings to see if your main app target is selected in the "Host Application" option. 

If your tests are hosted by the app, you can try commenting out the second `import_pods` to see if your tests still compile and the problem is fixed.

**Comment by plaetzchen** [comment]
@bgerstle When I do this my linker fails because it can't link to some frameworks I use. I had similar issues with AFNetworking and tried a solution by explicitly linking some but not all frameworks to the test target. I will try that for AnimtedGIFImageSerilization

**Comment by plaetzchen** [comment]
OK I fixed it by removing AnimatedGIFImageSerilization from import_pods and adding it only to my normal targets. Thank you for your support @bgerstle

**Comment by bgerstle** [comment]
Welcome, glad I was able to help
