### ISSUE TITLE
Play too fast

### ISSUE THREAD

**Issue by 90candy** [mattt/AnimatedGIFImageSerialization#32]

**Comment by 90candy** [comment]
How do I control the play speed?

**Comment by mattt** [comment]
You can control the duration of playback (and therefore the frame rate) using the [`AnimatedGIFImageSerialization -imageWithData:scale:duration:error:` method](https://github.com/mattt/AnimatedGIFImageSerialization/blob/master/AnimatedGIFImageSerialization/AnimatedGIFImageSerialization.h#L71-L74).
