### ISSUE TITLE
How to used on OSX?

### ISSUE THREAD

**Issue by MustangYM** [mattt/AnimatedGIFImageSerialization#33]
This is a great library, but it can't be used on OSX anymore, because the library of Mobile Services Core can't be found.

**Comment by mattt** [comment]
`AppKit` natively supports animated GIFs, so this library is unnecessary.

**Comment by MustangYM** [comment]
> `AppKit` 本机支持动画GIF，因此这个库是不必要的。

This is my question on stackoverflow, but it hasn't been solved yet. Can you help me to see it?
https://stackoverflow.com/questions/55759626/use-nsbitmapimagerep-transformed-gif?noredirect=1#comment98197706_55759626
